# Generated by Django 2.2.3 on 2020-12-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('nombre', models.TextField(max_length=100, unique=True, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('plato_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('nombre', models.TextField(max_length=100, unique=True, verbose_name='Plato')),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Categoria', verbose_name='Categoria')),
            ],
        ),
    ]
