# Generated by Django 2.2.3 on 2020-12-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Plato'),
        ),
    ]
