# Generated by Django 2.2.3 on 2021-01-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201231_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[{'PROCESO', 'En_proceso'}, {'Entregado', 'ENTREGADO'}, {'Pagado', 'PAGADO'}], default='PROCESO', max_length=10),
        ),
    ]
