# Generated by Django 2.2.3 on 2021-01-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210107_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoTerminado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Pedidos')),
            ],
        ),
    ]
