# Generated by Django 2.2.3 on 2021-01-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_pedidoterminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('PROCESO', 'En_proceso'), ('ENTREGADO', 'Entregado'), ('PAGADO', 'Pagado')], default='PROCESO', max_length=10),
        ),
    ]
