# Generated by Django 2.2.3 on 2021-01-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210112_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('PROCESO', 'En_proceso'), ('TERMINADO', 'Terminado'), ('PAGADO', 'Pagado')], default='PROCESO', max_length=10),
        ),
        migrations.DeleteModel(
            name='PedidoTerminado',
        ),
    ]
